language: cpp

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

before_install:
  - ifconfig -a

install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install libpcap-dev libssl-dev; fi

before_script:
  - mkdir build
  - cd build
  - cmake .. -DLIBTINS_ENABLE_CXX11=1
  - make tests

script:
  - ctest -V